#!/usr/bin/env python3
"""Generate the pre-rescaled JST pooled data bundle for the browser block-bootstrap engine.

Usage:
    python3 -m analysis.glide_path.generate_bundle          # default out path
    python3 -m analysis.glide_path.generate_bundle --out /path/to/jstData.ts

Downloads the JST R6 workbook on first use (cached under analysis/.data/).
Writes a TypeScript file with Float32Array and Int32Array constants encoding the
forward-CMA-rescaled pooled history and the segment-boundary arrays needed by
the browser's stationary block bootstrap.
"""

from __future__ import annotations

import argparse
import os
import sys

# Allow direct execution without an installed package.
if __package__ in (None, ""):
    _repo_root = os.path.dirname(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    )
    sys.path.insert(0, _repo_root)

import numpy as np

_DEFAULT_OUT = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
    "src", "utils", "glide-path", "jstData.ts",
)


def _format_float32_array(arr: np.ndarray) -> str:
    """Format a numpy array as a TypeScript Float32Array literal."""
    vals = ", ".join(f"{float(x):.8g}" for x in arr)
    return f"new Float32Array([{vals}])"


def _format_int32_array(arr: np.ndarray) -> str:
    """Format a numpy array as a TypeScript Int32Array literal."""
    vals = ", ".join(str(int(x)) for x in arr)
    return f"new Int32Array([{vals}])"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.strip())
    ap.add_argument("--out", default=_DEFAULT_OUT, help="output TypeScript file path")
    args = ap.parse_args(argv)

    from analysis.glide_path.recommender import PWL_CURVE, _forward_anchors
    from analysis.shared.jst_history import load_pooled_country_returns, rescale_to_targets

    print("Loading JST pooled history...")
    raw = load_pooled_country_returns()
    print(
        f"  {raw.observations} observations · {raw.country_count} countries · "
        f"{raw.start_year}–{raw.end_year}"
    )

    eq_mean, eq_vol, bond_mean, bond_vol = _forward_anchors(PWL_CURVE, 2.1, True)
    print(
        f"  Forward anchors: equity {eq_mean*100:.4f}% ± {eq_vol*100:.4f}%  "
        f"bonds {bond_mean*100:.4f}% ± {bond_vol*100:.4f}%"
    )

    rescaled = rescale_to_targets(
        raw,
        equity_mean=eq_mean,
        equity_vol=eq_vol,
        fixed_income_mean=bond_mean,
        fixed_income_vol=bond_vol,
        label_suffix="forward-CMA rescaled",
    )

    equity = rescaled.equity.astype(np.float32)
    fixed_income = rescaled.fixed_income.astype(np.float32)

    # Compute per-observation segment-start and segment-length arrays.
    # These are the same arrays _segment_bounds produces in jst_history.py; we
    # pre-compute them here so the browser can run the block bootstrap without
    # needing to re-derive segment structure at runtime.
    segment_ids = raw.segment_ids
    n = len(segment_ids)
    change = np.flatnonzero(np.diff(segment_ids) != 0) + 1
    starts = np.concatenate(([0], change))
    ends = np.concatenate((change, [n]))
    seg_start = np.empty(n, dtype=np.int32)
    seg_len = np.empty(n, dtype=np.int32)
    for s, e in zip(starts, ends):
        seg_start[s:e] = s
        seg_len[s:e] = e - s

    print(f"Writing {args.out} ...")
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as fh:
        fh.write(
            "// AUTO-GENERATED by analysis/glide_path/generate_bundle.py — do not edit.\n"
            "// JST R6 pooled real returns, affine-rescaled to forward-CMA marginals.\n"
            f"// {raw.observations} observations · {raw.country_count} countries · "
            f"{raw.start_year}–{raw.end_year}\n"
            f"// Equity  mean {eq_mean*100:.4f}%  vol {eq_vol*100:.4f}%\n"
            f"// Bonds   mean {bond_mean*100:.4f}%  vol {bond_vol*100:.4f}%\n\n"
        )
        fh.write(f"export const JST_OBSERVATIONS = {raw.observations};\n\n")
        fh.write(f"export const JST_EQUITY = {_format_float32_array(equity)};\n\n")
        fh.write(f"export const JST_BOND = {_format_float32_array(fixed_income)};\n\n")
        fh.write(f"export const JST_SEG_START = {_format_int32_array(seg_start)};\n\n")
        fh.write(f"export const JST_SEG_LEN = {_format_int32_array(seg_len)};\n")

    size_kb = os.path.getsize(args.out) / 1024
    print(f"Done: {size_kb:.1f} KB")


if __name__ == "__main__":
    main()
