export const DEFAULTS = {
  monthlyRent: 3500,
  rentIncreaseRate: 2.5,
  initialHomePrice: 1000000,
  homePriceGrowthRate: 2.5,
  buyersClosingCostPercentage: 2.5,
  sellersClosingCostPercentage: 4,
  propertyTaxRate: 1,
  maintenanceCostPercentage: 1.5,
  downPaymentPercentage: 20,
  annualMortgageInterestRate: 4.5,
  mortgageTerm: 25,
  investmentReturnRate: 6,
  dividendYield: 1.5,
  dividendTaxRate: 30,
  investmentGainTax: 15,
};

export const PRESETS = [
  { label: "Defaults", values: DEFAULTS },
  {
    label: "Bay Street Condo",
    values: {
      ...DEFAULTS,
      monthlyRent: 3000,
      rentIncreaseRate: 2.5,
      initialHomePrice: 800000,
      homePriceGrowthRate: 3,
      downPaymentPercentage: 10,
      mortgageTerm: 30,
      maintenanceCostPercentage: 2,
      propertyTaxRate: 0.65,
      buyersClosingCostPercentage: 4,
      sellersClosingCostPercentage: 4,
    },
  },
  {
    label: "Vancouver Townhouse",
    values: {
      ...DEFAULTS,
      monthlyRent: 4000,
      rentIncreaseRate: 2.5,
      initialHomePrice: 1300000,
      homePriceGrowthRate: 3,
      maintenanceCostPercentage: 1.5,
      propertyTaxRate: 0.3,
      buyersClosingCostPercentage: 2.5,
      sellersClosingCostPercentage: 4,
      mortgageTerm: 30,
    },
  },
  {
    label: "Calgary SFH",
    values: {
      ...DEFAULTS,
      monthlyRent: 2500,
      rentIncreaseRate: 2,
      initialHomePrice: 700000,
      homePriceGrowthRate: 2.5,
      maintenanceCostPercentage: 1.5,
      propertyTaxRate: 0.7,
      buyersClosingCostPercentage: 0.75,
      sellersClosingCostPercentage: 4,
    },
  },
];
