export const DEFAULTS = {
  monthlyRent: 5000,
  rentIncreaseRate: 2.5,
  initialHomePrice: 1000000,
  homePriceGrowthRate: 2.5,
  buyersClosingCostPercentage: 2.5,
  sellersClosingCostPercentage: 4,
  propertyTaxRate: 1,
  maintenanceCostPercentage: 1.5,
  downPaymentPercentage: 20,
  annualMortgageInterestRate: 4.5,
  amortizationPeriod: 25,
  investmentReturnRate: 6,
  dividendYield: 1.5,
  dividendTaxRate: 30,
  capitalGainTaxRate: 15,
  homePriceGrowthSigma: 1.5,
  investmentReturnSigma: 2,
  rentIncreaseSigma: 0.75,
  mortgageRateSigma: 0.5,
  maintenanceSigma: 0.4,
  propertyTaxSigma: 0.15,
  dividendYieldSigma: 0.3,
};

export const PRESETS = [
  { label: "Defaults", values: DEFAULTS },
  {
    label: "Bay Street Condo",
    values: {
      ...DEFAULTS,
      monthlyRent: 2700,
      rentIncreaseRate: 2.5,
      initialHomePrice: 798000,
      homePriceGrowthRate: 3,
      downPaymentPercentage: 10,
      amortizationPeriod: 30,
      maintenanceCostPercentage: 1.53,
      propertyTaxRate: 0.49,
      buyersClosingCostPercentage: 4,
      sellersClosingCostPercentage: 4,
    },
  },
  {
    label: "Vancouver Townhouse",
    values: {
      ...DEFAULTS,
      monthlyRent: 4000,
      rentIncreaseRate: 2.5,
      initialHomePrice: 1198000,
      homePriceGrowthRate: 3,
      maintenanceCostPercentage: 1.99,
      propertyTaxRate: 0.29,
      buyersClosingCostPercentage: 2.5,
      sellersClosingCostPercentage: 4,
      amortizationPeriod: 30,
    },
  },
  {
    label: "Calgary SFH",
    values: {
      ...DEFAULTS,
      monthlyRent: 2800,
      rentIncreaseRate: 2,
      initialHomePrice: 625000,
      homePriceGrowthRate: 2.5,
      maintenanceCostPercentage: 1.5,
      propertyTaxRate: 0.62,
      buyersClosingCostPercentage: 0.75,
      sellersClosingCostPercentage: 4,
    },
  },
];
